import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "../lib/providers"; // next-themes provider
import { ClerkProvider } from "@clerk/nextjs"; // <-- use directly

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
                    bg-gray-100 dark:bg-gray-900
                    text-gray-800 dark:text-gray-200
                    transition-colors duration-300`}
      >
        <Providers>
          <ClerkProvider>
            <Navbar />
            {children}
            <Footer />
          </ClerkProvider>
        </Providers>
      </body>
    </html>
  );
}
